#!/bin/bash
sudo yum update -y
sudo yum install docker -y
sudo systemctl start docker
mkdir /home/ec2-user/deathrun

IPV4=$(curl 169.254.169.254/latest/meta-data/public-ipv4)
aws route53 change-resource-record-sets --hosted-zone-id Z3OPAVCB13L0BG --change-batch "{
   \"Changes\":[
      {
         \"Action\":\"UPSERT\",
         \"ResourceRecordSet\":{
            \"Name\":\"gmod.dr.itisamystery.com\",
            \"ResourceRecords\":[
               {
                  \"Value\":\"$IPV4\"
               }
            ],
            \"Type\":\"A\",
            \"TTL\":300
         }
      }
   ]
}"

docker run -idt -e "GLST=8FC53DE1A2A7E665FABF7197AEBA09DF" -e "WORKSHOPCOLLECTIONID=2227527602" -e "WORKSHOPDL=2227527602" -e "WORKSHOP=2227527602" -e "GAMEMODE=deathrun" -e "MAP=dr_minecraft" -p 27015:27015/tcp -p 27015:27015/udp -v /home/ec2-user/deathrun:/opt/steam hackebein/garrysmod
